export {default as Logo} from './ghost-svgrepo-com.svg'
export {default as MailIcon} from './email-18-svgrepo-com.svg'
export {default as Ghost} from './ghost-only.svg'
export { default as OutLookLogo } from './icons8-microsoft-outlook.svg'
export { default as GmailLogo } from './icons8-gmail.svg'
